function dx_xd1 = dx_xd1(t)
%DX_XD1
%    DX_XD1 = DX_XD1(T)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    13-Sep-2018 10:53:42

t2 = conj(t);
t3 = t2.*pi.*(1.0./5.0);
dx_xd1 = [pi.*cos(t3).*(3.0./2.0e2);0.0;pi.*sin(t3).*(-3.0./2.0e2)];
